baseURL: 'https://nakatarui.github.io/'
languageCode: 'ja-jp'
title: "BI BO RO KU room"
theme: 'PaperMod'
publishDir: 'docs'
enableRobotsTXT: false
buildDrafts: false
params:
  title: "BI BO RO KU room"
  ShowReadingTime: false
  defaultTheme: dark # dark. light
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  disableSpecial1stPost: false
  env: production
#  googleAnalyticsID: G-YPJGNCF242
assets:
  favicon: ""
menu:
  main:
     - identifier: SNS
       name: Github
       url: https://github.com/nakatarui
       weight: 10
